### ISSUE TITLE
Extent of preservation; fixing typos

### ISSUE THREAD

**Issue by aidan-mueller** [cobelu/Long-EZ#2]
The current text of the README says the following:
> My job is to digitize the plans as they were originally published.

Does this extend to keeping any original typos? For example, in the first table in chapter 1, the word "checklist" is written as 2 separate words even though it is typically spelled as 1 word.

It would be good to have some clarification on exactly what should be preserved and what can be edited.

**Comment by cobelu** [comment]
Hi Aidan,

No internet at the house today, but I’ll try to get an attempt at a style guide together for you today. 

Thanks,
-C

**Comment by cobelu** [comment]
Howdy,

An attempt at a style guide has been added to the repo.
Please, bear with me as I have not been a part of a large project before.
Lemme know if I can do anything else to assist.

Best,
-C
